[package]
name = "rdd"
version = "0.0.1"
authors = ["msk-ono <aaikmnoos@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fnv = "1.0.3"
